services:
  libb-nlp:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TZ: ${TZ:-UTC}
        OPENROUTER_API_KEY: ${OPENROUTER_API_KEY}
        OPENROUTER_REFERER: ${OPENROUTER_REFERER}
        OPENROUTER_TITLE: ${OPENROUTER_TITLE}
    restart: unless-stopped
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPOSITORY}:${IMAGE_TAG}
    ports:
      - "8000:8000"
    environment:
      - ENV=${ENV}
      - TZ=${TZ:-UTC}
      - OPENROUTER_API_KEY
      - OPENROUTER_REFERER
      - OPENROUTER_TITLE
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - ~/.cache/${ECR_REPOSITORY}:/root/.cache/${ECR_REPOSITORY}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
