[tool.poetry]
name = "libb-nlp"
version = "0.1.0"
description = ""
authors = ["bissli <bissli.xyz@protonmail.com>"]
readme = "README.md"
packages = [{ include = "lnlp", from = "src" }]
repository = "https://github.com/bissli/libb-nlp"

[tool.poetry.dependencies]
python = "^3.9"
langchain = "^0.3.14"
seaborn = "*"
spacy = "*"
pysbd = "*"
sentence-transformers = "*"
torch = { version = "*", optional = true }
torchvision = { version = "*", optional = true }
fastapi = "^0.104.0"
uvicorn = "^0.24.0"
pydantic = "^2.4.2"
pdfplumber = "*"
python-multipart = "*"

# = test
asserts = { version = "*", optional = true }
pytest = { version = "*", optional = true }
pytest-docker = { version = "*", optional = true }
pdbp = { version = "*", optional = true }
bump2version = { version = "*", optional = true }
boto3 = { version = '^1.36.18', optional = true }
docker = { version = '*', optional = true }

[tool.poetry.group.cpu]
optional = true

[tool.poetry.group.cpu.dependencies]
torch = { version = "*", source = "torch_cpu", markers = "extra=='cpu' and extra!='gpu'" }
torchvision = { version = "*", source = "torch_cpu", markers = "extra=='cpu' and extra!='gpu'" }

[tool.poetry.group.gpu]
optional = true

[tool.poetry.group.gpu.dependencies]
torch = { version = "*", source = "torch_cuda", markers = "extra=='gpu' and extra!='cpu'" }
torchvision = { version = "*", source = "torch_cuda", markers = "extra=='gpu' and extra!='cpu'" }

[tool.poetry.extras]
test = [
  "asserts",
  "pdbp",
  "pytest",
  "bump2version",
  "boto3",
  "docker",
  "pytest-docker"
]
cpu = ["torch", "torchvision"]
gpu = ["torch", "torchvision"]

[[tool.poetry.source]]
name = "torch_cpu"
url = "https://download.pytorch.org/whl/cpu"
priority = "explicit"

[[tool.poetry.source]]
name = "torch_cuda"
url = "https://download.pytorch.org/whl/cu121"
priority = "explicit"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
